tasks:
  - name: Gitpod tasks
    command: ./start.sh
       
    env:
      RefArch_ADYEN_ENVIRONMENT: TEST
      RefArch_SYSTEM_INTEGRATOR_NAME: AdyenDevRelGitpod

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
