tasks:
  - name: Gitpod start script
    command: ./gitpod_start.sh
    
    env:
      RefArch_ADYEN_ENVIRONMENT: TEST
      RefArch_SYSTEM_INTEGRATOR_NAME: AdyenDevRelGitpod

ports:
  - name: Storefront
    port: 3000
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint